# Uncomment the next line to define a global platform for your project
# platform :ios, ’10.0’
source 'https://github.com/CocoaPods/Specs.git'

target 'DJ APP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DJ APP

pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'JTAppleCalendar','~> 7.1.4'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

  target 'DJ APPTests' do
    inherit! :search_paths
    # Pods for testing
  end



  target 'DJ APPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
